---
- name: Gather remote host info
  hosts: tstlaunched
  remote_user: ubuntu
  vars:
    region: "eu-central-1"
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
    ansible_ssh_private_key_file: ~/.ssh/techstarter.pem
  tasks:
    - name: get remote instance metadata
      ec2_metadata_facts:
    - name: destroy the instance with instance id
      ec2:
           state: 'absent'
           region: "{{ region }}"
           instance_ids: "{{ ansible_ec2_instance_id }}"
      delegate_to: localhost
